spring:
  redis:
    host: #地址
    port: #端口
    password: #密码
    timeout: # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: # 连接池中的最大空闲连接 默认 8
        min-idle: # 连接池中的最小空闲连接 默认 0